---
driver:
  name: vagrant
  provider: hyperv

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04  
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 80}]
      - ["forwarded_port", {guest: 22, host: 22}]
      - ["private_network", {ip: "192.168.33.33"}]

suites:
  - name: default
    run_list:
      - recipe[WinBuntuWeb::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: