---
driver:
  name: hyperv
  parent_vhd_folder: F:\Hyper-V
  parent_vhd_name: WindowsServer2016.vhdx
  vm_switch: ExternalSwitch
  memory_startup_bytes: 2GB

provisioner:
  name: chef_zero

transport:
  name: winrm
  elevated: true
  password: 123Passord

verifier:
  name: inspec
  
platforms:
    - name: windows-server-2016


suites:
  - name: default
    run_list:
      - recipe[WinBuntuWeb::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: